package com.example.bankloginsystem

import android.annotation.SuppressLint
import android.content.ContentValues
import android.content.Context
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

/**
 * Represents a book record from the user's library, combining details from both the `books`
 * and `user_library` tables. This data class is used to hold the complete information for
 * a book that a user has added to their shelf.
 *
 * @property id The unique ID of the entry in the `user_library` table.
 * @property userId The ID of the user who owns this book entry.
 * @property bookId The ID of the book in the central `books` table.
 * @property name The title of the book.
 * @property author The author of the book.
 * @property category The main category of the book (e.g., FICTION, NON-FICTION).
 * @property genre The specific genre of the book (e.g., Fantasy, Sci-Fi).
 * @property coverUri A string URI pointing to the book's cover image, which may be local or a remote URL.
 * @property status The user's reading status for the book (e.g., "Currently Reading", "Completed").
 * @property firebaseKey The unique key generated by Firebase Realtime Database for this book entry, used for synchronization.
 */
data class UserBook(
    val id: Int, 
    val userId: Int,
    val bookId: Int,
    val name: String,
    val author: String,
    val category: String,
    val genre: String,
    val coverUri: String?,
    val status: String?,
    val firebaseKey: String? 
)

/**
 * This class is a SQLiteOpenHelper that manages database creation and version management.
 * The SQLite database is a form of internal storage used here to persist user data.
 * This is a good choice for storing structured data like user accounts and book information.
 *
 * @param context The application context.
 */
class DatabaseHelper(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {

    /**
     * A companion object to hold constants for the database schema, including table and column names.
     * Using constants helps prevent typos and makes the code more maintainable.
     */
    companion object {
        private const val DATABASE_NAME = "AppDatabase.db"
        private const val DATABASE_VERSION = 2 // Incremented the version to reflect schema changes.
        const val TABLE_USERS = "users"
        const val COLUMN_ID = "id"
        const val COLUMN_FIRST_NAME = "first_name"
        const val COLUMN_LAST_NAME = "last_name"
        const val COLUMN_GENDER = "gender"
        const val COLUMN_EMAIL = "email"
        const val COLUMN_PASSWORD = "password" 
        const val COLUMN_PHONE_NUMBER = "phone_number"
        const val COLUMN_BALANCE = "balance"

        // Table for all unique books to avoid redundancy.
        const val BOOKS_TABLE_NAME = "books"
        const val COLUMN_BOOK_ID = "book_id"
        const val COLUMN_BOOK_NAME = "name"
        const val COLUMN_AUTHOR = "author"
        const val COLUMN_CATEGORY = "category"
        const val COLUMN_GENRE = "genre"
        const val COLUMN_COVER_URI = "cover_uri"

        // Linking table for the user's personal library.
        const val USER_LIBRARY_TABLE_NAME = "user_library"
        const val COLUMN_LIBRARY_ID = "library_id" // Primary key for this relationship.
        const val COLUMN_USER_ID_FK = "user_id" // Foreign key to the main users table.
        const val COLUMN_BOOK_ID_FK = "book_id" // Foreign key to the books table.
        const val COLUMN_STATUS = "status" // User-specific reading status.
        const val COLUMN_FIREBASE_KEY = "firebase_key" // Key for syncing with Firebase.
    }

    /**
     * Called when the database is created for the first time.
     * This is where the creation of tables and the initial population of the tables should happen.
     *
     * @param db The database.
     */
    override fun onCreate(db: SQLiteDatabase?) {
        val createTable = """
            CREATE TABLE $TABLE_USERS (
            $COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
            $COLUMN_FIRST_NAME TEXT,
            $COLUMN_LAST_NAME TEXT,
            $COLUMN_GENDER TEXT,
            $COLUMN_EMAIL TEXT,
            $COLUMN_PASSWORD TEXT,
            $COLUMN_PHONE_NUMBER TEXT,
            $COLUMN_BALANCE REAL
            );
        """.trimIndent()
        db?.execSQL(createTable)

        // SQL statement to create the central 'books' table with a unique constraint on name and author.
        val createBooksTableQuery = """
            CREATE TABLE $BOOKS_TABLE_NAME (
                $COLUMN_BOOK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
                $COLUMN_BOOK_NAME TEXT NOT NULL,
                $COLUMN_AUTHOR TEXT NOT NULL,
                $COLUMN_CATEGORY TEXT,
                $COLUMN_GENRE TEXT,
                $COLUMN_COVER_URI TEXT,
                UNIQUE ($COLUMN_BOOK_NAME, $COLUMN_AUTHOR)
            );
        """.trimIndent()

        // SQL statement to create the 'user_library' linking table.
        val createUserLibraryTableQuery = """
            CREATE TABLE $USER_LIBRARY_TABLE_NAME (
                $COLUMN_LIBRARY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
                $COLUMN_USER_ID_FK INTEGER NOT NULL,
                $COLUMN_BOOK_ID_FK INTEGER NOT NULL,
                $COLUMN_STATUS TEXT,
                $COLUMN_FIREBASE_KEY TEXT,
                FOREIGN KEY ($COLUMN_USER_ID_FK) REFERENCES users(id),
                FOREIGN KEY ($COLUMN_BOOK_ID_FK) REFERENCES $BOOKS_TABLE_NAME($COLUMN_BOOK_ID),
                UNIQUE ($COLUMN_USER_ID_FK, $COLUMN_BOOK_ID_FK)
            );
        """.trimIndent()

        db?.execSQL(createBooksTableQuery)
        db?.execSQL(createUserLibraryTableQuery)
    }

    /**
     * Called when the database needs to be upgraded.
     * This method will be called when the database version is increased.
     * For a simple implementation, we just drop the old tables and create new ones.
     *
     * @param db The database.
     * @param oldVersion The old database version.
     * @param newVersion The new database version.
     */
    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        db?.execSQL("DROP TABLE IF EXISTS $USER_LIBRARY_TABLE_NAME")
        db?.execSQL("DROP TABLE IF EXISTS $BOOKS_TABLE_NAME")
        db?.execSQL("DROP TABLE IF EXISTS $TABLE_USERS")
        onCreate(db)
    }

    /**
     * Inserts a new user into the `users` table.
     *
     * @return `true` if the user was inserted successfully, `false` otherwise.
     */
    fun insertUser(
        firstName: String,
        lastName: String,
        gender: String,
        email: String,
        password: String,
        phoneNumber: String,
        balance: Double
    ) : Boolean {
        val db = this.writableDatabase
        return try {
            val values = ContentValues().apply {
                put(COLUMN_FIRST_NAME, firstName)
                put(COLUMN_LAST_NAME, lastName)
                put(COLUMN_GENDER, gender)
                put(COLUMN_EMAIL, email)
                put(COLUMN_PASSWORD, password)
                put(COLUMN_PHONE_NUMBER, phoneNumber)
                put(COLUMN_BALANCE, balance)
            }
            val id = db.insert(TABLE_USERS, null, values)
            id != -1L
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }

    /**
     * Checks if a user with the given email already exists in the database.
     *
     * @param email The email to check.
     * @return `true` if the user exists, `false` otherwise.
     */
    fun userExists(email: String) : Boolean {
        val db = this.readableDatabase
        var cursor: Cursor? = null
        return try {
            cursor = db.rawQuery("SELECT $COLUMN_ID FROM $TABLE_USERS WHERE $COLUMN_EMAIL = ?", arrayOf(email))
            val exists = cursor.count > 0
            exists
        } finally {
            cursor?.close()
        }
    }

    /**
     * Retrieves a user from the database by their email address.
     *
     * @param email The email of the user to retrieve.
     * @return A [Cursor] containing the user's data. The caller is responsible for closing the cursor.
     */
    fun getUserByEmail(email: String): Cursor {
        val db = this.readableDatabase
        return db.rawQuery("SELECT * FROM $TABLE_USERS WHERE $COLUMN_EMAIL = ?", arrayOf(email))
    }

    /**
     * Inserts a book into a user's library. This is a two-step process:
     * 1. It finds or creates an entry for the book in the central `books` table.
     * 2. It creates an entry in the `user_library` table linking the user to that book.
     *
     * @return `true` if the book was successfully added to the user's library, `false` otherwise.
     */
    @SuppressLint("UseKtx")
    fun insertUserBook(
        userId: Int,
        name: String,
        author: String,
        category: String,
        genre: String,
        coverUri: String?,
        status: String?,
        firebaseKey: String?
    ): Boolean {
        val db = this.writableDatabase
        db.beginTransaction() // Use a transaction for this multi-step operation to ensure atomicity.
        try {
            // Step 1: Find or create the book in the central `books` table to get its ID.
            var bookId = findBook(db, name, author)
            if (bookId == -1L) { // If the book doesn't exist, create it.
                val bookValues = ContentValues().apply {
                    put(COLUMN_BOOK_NAME, name)
                    put(COLUMN_AUTHOR, author)
                    put(COLUMN_CATEGORY, category)
                    put(COLUMN_GENRE, genre)
                    put(COLUMN_COVER_URI, coverUri)
                }
                bookId = db.insert(BOOKS_TABLE_NAME, null, bookValues)
            }

            if (bookId == -1L) return false // If book creation failed, abort.

            // Step 2: Add the book to the user's personal library, including the Firebase key.
            val libraryValues = ContentValues().apply {
                put(COLUMN_USER_ID_FK, userId)
                put(COLUMN_BOOK_ID_FK, bookId)
                put(COLUMN_STATUS, status)
                put(COLUMN_FIREBASE_KEY, firebaseKey) // Save the Firebase key for sync.
            }
            // Use CONFLICT_IGNORE to prevent crashing if the user already has the book.
            val result = db.insertWithOnConflict(USER_LIBRARY_TABLE_NAME, null, libraryValues, SQLiteDatabase.CONFLICT_IGNORE)

            db.setTransactionSuccessful() // Commit the transaction.
            return result != -1L
        } catch (e: Exception) {
            e.printStackTrace()
            return false
        } finally {
            db.endTransaction() // End the transaction (either commit or rollback).
            db.close() // Always close the database connection.
        }
    }

    /**
     * Searches for a book in the `books` table by its name and author.
     * @param db The readable database instance.
     * @param name The name of the book to find.
     * @param author The author of the book to find.
     * @return The ID of the book if found, otherwise -1.
     */
    private fun findBook(db: SQLiteDatabase, name: String, author: String): Long {
        var cursor: Cursor? = null
        try {
            cursor = db.query(
                BOOKS_TABLE_NAME,
                arrayOf(COLUMN_BOOK_ID),
                "$COLUMN_BOOK_NAME = ? AND $COLUMN_AUTHOR = ?",
                arrayOf(name, author),
                null, null, null
            )
            if (cursor.moveToFirst()) {
                return cursor.getLong(cursor.getColumnIndexOrThrow(COLUMN_BOOK_ID))
            }
        } finally {
            cursor?.close()
        }
        return -1L
    }

    /**
     * Retrieves all books belonging to a specific user.
     * It performs a JOIN between the `user_library` and `books` tables to gather all relevant data.
     * @param userId The ID of the user whose books are to be retrieved.
     * @return A list of `UserBook` objects, each representing a book in the user's library.
     */
    fun getBooksByUser(userId: Int): List<UserBook> {
        val bookList = mutableListOf<UserBook>()
        val db = this.readableDatabase
        // The JOIN query combines rows from both tables based on the book_id.
        val query = """
            SELECT
                lib.$COLUMN_LIBRARY_ID, lib.$COLUMN_USER_ID_FK, lib.$COLUMN_BOOK_ID_FK, lib.$COLUMN_STATUS, lib.$COLUMN_FIREBASE_KEY,
                b.$COLUMN_BOOK_NAME, b.$COLUMN_AUTHOR, b.$COLUMN_CATEGORY, b.$COLUMN_GENRE, b.$COLUMN_COVER_URI
            FROM
                $USER_LIBRARY_TABLE_NAME lib
            JOIN
                $BOOKS_TABLE_NAME b ON lib.$COLUMN_BOOK_ID_FK = b.$COLUMN_BOOK_ID
            WHERE
                lib.$COLUMN_USER_ID_FK = ?
        """.trimIndent()

        var cursor: Cursor? = null
        try {
            cursor = db.rawQuery(query, arrayOf(userId.toString()))
            if (cursor.moveToFirst()) {
                do {
                    // Safely get nullable values from the cursor.
                    val coverUriIndex = cursor.getColumnIndexOrThrow(COLUMN_COVER_URI)
                    val coverUri = if (cursor.isNull(coverUriIndex)) null else cursor.getString(coverUriIndex)

                    val statusIndex = cursor.getColumnIndexOrThrow(COLUMN_STATUS)
                    val status = if (cursor.isNull(statusIndex)) null else cursor.getString(statusIndex)
                    
                    val firebaseKeyIndex = cursor.getColumnIndexOrThrow(COLUMN_FIREBASE_KEY)
                    val firebaseKey = if (cursor.isNull(firebaseKeyIndex)) null else cursor.getString(firebaseKeyIndex)

                    val book = UserBook(
                        id = cursor.getInt(cursor.getColumnIndexOrThrow(COLUMN_LIBRARY_ID)),
                        userId = cursor.getInt(cursor.getColumnIndexOrThrow(COLUMN_USER_ID_FK)),
                        bookId = cursor.getInt(cursor.getColumnIndexOrThrow(COLUMN_BOOK_ID_FK)),
                        name = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_BOOK_NAME)),
                        author = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_AUTHOR)),
                        category = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_CATEGORY)),
                        genre = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_GENRE)),
                        coverUri = coverUri,
                        status = status,
                        firebaseKey = firebaseKey
                    )
                    bookList.add(book)
                } while (cursor.moveToNext())
            }
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            cursor?.close()
            db.close()
        }
        return bookList
    }

    /**
     * Updates the status of a book in the user's library.
     *
     * @param libraryId The ID of the book in the `user_library` table.
     * @param newStatus The new status to set for the book.
     * @return The number of rows affected.
     */
    fun updateBookStatus(libraryId: Int, newStatus: String): Int {
        val db = this.writableDatabase
        val values = ContentValues().apply {
            put(COLUMN_STATUS, newStatus)
        }
        return db.update(USER_LIBRARY_TABLE_NAME, values, "$COLUMN_LIBRARY_ID = ?", arrayOf(libraryId.toString()))
    }

    /**
     * Deletes a book from a user's library.
     *
     * @param libraryId The ID of the book in the `user_library` table.
     * @return The number of rows affected.
     */
    fun deleteBookFromLibrary(libraryId: Int): Int {
        val db = this.writableDatabase
        return db.delete(USER_LIBRARY_TABLE_NAME, "$COLUMN_LIBRARY_ID = ?", arrayOf(libraryId.toString()))
    }

    /**
     * Updates the cover image URI of a book in the central `books` table.
     *
     * @param bookId The ID of the book in the `books` table.
     * @param newCoverUri The new cover image URI to set.
     * @return The number of rows affected.
     */
    fun updateBookCover(bookId: Int, newCoverUri: String): Int {
        val db = this.writableDatabase
        val values = ContentValues().apply {
            put(COLUMN_COVER_URI, newCoverUri)
        }
        return db.update(BOOKS_TABLE_NAME, values, "$COLUMN_BOOK_ID = ?", arrayOf(bookId.toString()))
    }
}
