package com.example.bankloginsystem

import android.annotation.SuppressLint
import android.content.ContentValues
import android.content.Context
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

/**
 * Represents a book record from the user's library, combining details from both the `books`
 * and `user_library` tables. This data class is used to hold the complete information for
 * a book that a user has added to their shelf.
 *
 * @property id The unique ID of the entry in the `user_library` table.
 * @property userId The ID of the user who owns this book entry.
 * @property bookId The ID of the book in the central `books` table.
 * @property name The title of the book.
 * @property author The author of the book.
 * @property category The main category of the book (e.g., FICTION, NON-FICTION).
 * @property genre The specific genre of the book (e.g., Fantasy, Sci-Fi).
 * @property coverUri A string URI pointing to the book's cover image, which may be local or a remote URL.
 * @property status The user's reading status for the book (e.g., "Currently Reading", "Completed").
 * @property firebaseKey The unique key generated by Firebase Realtime Database for this book entry, used for synchronization.
 */
data class UserBook(
    val id: Int, // This will be the ID from the user_library table
    val userId: Int,
    val bookId: Int,
    val name: String,
    val author: String,
    val category: String,
    val genre: String,
    val coverUri: String?,
    val status: String?,
    val firebaseKey: String? // Added to link with Firebase Realtime Database
)

/**
 * Manages the local SQLite database for storing book information. This helper class handles
 * database creation, version management, and all CRUD (Create, Read, Update, Delete) operations
 * for the user's book library.
 *
 * The database is designed with two main tables:
 * 1. `books`: A central repository of all unique books to avoid data duplication. Each book
 *    (defined by its name and author) has only one entry here.
 * 2. `user_library`: A linking table that connects a user to a book from the `books` table.
 *    It also stores user-specific information, like the reading status and the Firebase key.
 *
 * @param context The application context, used to access the database.
 */
class UserBooksDatabaseHelper(context: Context)
    : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {

    /**
     * Companion object to hold constants related to the database schema.
     * This includes the database name, version, table names, and column names.
     */
    companion object {
        // A best practice for database schema changes is to increment the version number.
        // This ensures that the onUpgrade method is called, allowing for smooth schema migration.
        private const val DATABASE_NAME = "User_Books_v3.db"
        private const val DATABASE_VERSION = 2 // Incremented version to trigger onUpgrade

        // Table for all unique books to avoid redundancy.
        const val BOOKS_TABLE_NAME = "books"
        const val COLUMN_BOOK_ID = "book_id"
        const val COLUMN_BOOK_NAME = "name"
        const val COLUMN_AUTHOR = "author"
        const val COLUMN_CATEGORY = "category"
        const val COLUMN_GENRE = "genre"
        const val COLUMN_COVER_URI = "cover_uri"

        // Linking table for the user's personal library.
        const val USER_LIBRARY_TABLE_NAME = "user_library"
        const val COLUMN_LIBRARY_ID = "id" // Primary key for this relationship.
        const val COLUMN_USER_ID_FK = "user_id" // Foreign key to the main users table.
        const val COLUMN_BOOK_ID_FK = "book_id" // Foreign key to the books table.
        const val COLUMN_STATUS = "status" // User-specific reading status.
        const val COLUMN_FIREBASE_KEY = "firebase_key" // Key for syncing with Firebase.
    }

    /**
     * Called when the database is created for the first time. This is where the
     * DDL (Data Definition Language) for creating tables should be executed.
     * @param db The SQLiteDatabase instance.
     */
    override fun onCreate(db: SQLiteDatabase?) {
        // SQL statement to create the central 'books' table with a unique constraint on name and author.
        val createBooksTableQuery = """
            CREATE TABLE $BOOKS_TABLE_NAME (
                $COLUMN_BOOK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
                $COLUMN_BOOK_NAME TEXT NOT NULL,
                $COLUMN_AUTHOR TEXT NOT NULL,
                $COLUMN_CATEGORY TEXT,
                $COLUMN_GENRE TEXT,
                $COLUMN_COVER_URI TEXT,
                UNIQUE ($COLUMN_BOOK_NAME, $COLUMN_AUTHOR)
            );
        """.trimIndent()

        // SQL statement to create the 'user_library' linking table.
        val createUserLibraryTableQuery = """
            CREATE TABLE $USER_LIBRARY_TABLE_NAME (
                $COLUMN_LIBRARY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
                $COLUMN_USER_ID_FK INTEGER NOT NULL,
                $COLUMN_BOOK_ID_FK INTEGER NOT NULL,
                $COLUMN_STATUS TEXT,
                $COLUMN_FIREBASE_KEY TEXT,
                FOREIGN KEY ($COLUMN_USER_ID_FK) REFERENCES users(id),
                FOREIGN KEY ($COLUMN_BOOK_ID_FK) REFERENCES $BOOKS_TABLE_NAME($COLUMN_BOOK_ID),
                UNIQUE ($COLUMN_USER_ID_FK, $COLUMN_BOOK_ID_FK)
            );
        """.trimIndent()

        db?.execSQL(createBooksTableQuery)
        db?.execSQL(createUserLibraryTableQuery)
    }

    /**
     * Called when the database needs to be upgraded. This method allows for altering the
     * database schema when the `DATABASE_VERSION` is incremented.
     * @param db The SQLiteDatabase instance.
     * @param oldVersion The old database version.
     * @param newVersion The new database version.
     */
    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        // A simple migration strategy: if the old version is less than 2, add the new column.
        if (oldVersion < 2) {
            db?.execSQL("ALTER TABLE $USER_LIBRARY_TABLE_NAME ADD COLUMN $COLUMN_FIREBASE_KEY TEXT")
        }
    }

    /**
     * Called when the database needs to be downgraded. Downgrading can be complex and risk
     * data loss, so it's often handled simply or avoided.
     */
    override fun onDowngrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        // To avoid data loss, we don't automatically drop columns on downgrade.
        // If you need to downgrade, you'll have to handle it manually.
    }

    /**
     * Inserts a book into a user's library. This is a two-step process:
     * 1. It finds or creates an entry for the book in the central `books` table.
     * 2. It creates an entry in the `user_library` table linking the user to that book.
     *
     * @return True if the book was successfully added to the user's library, false otherwise.
     */
    @SuppressLint("UseKtx")
    fun insertUserBook(
        userId: Int,
        name: String,
        author: String,
        category: String,
        genre: String,
        coverUri: String?,
        status: String?,
        firebaseKey: String? // Added firebaseKey parameter
    ): Boolean {
        val db = this.writableDatabase
        db.beginTransaction() // Use a transaction for this multi-step operation to ensure atomicity.
        try {
            // Step 1: Find or create the book in the central `books` table to get its ID.
            var bookId = findBook(db, name, author)
            if (bookId == -1L) { // If the book doesn't exist, create it.
                val bookValues = ContentValues().apply {
                    put(COLUMN_BOOK_NAME, name)
                    put(COLUMN_AUTHOR, author)
                    put(COLUMN_CATEGORY, category)
                    put(COLUMN_GENRE, genre)
                    put(COLUMN_COVER_URI, coverUri)
                }
                bookId = db.insert(BOOKS_TABLE_NAME, null, bookValues)
            }

            if (bookId == -1L) return false // If book creation failed, abort.

            // Step 2: Add the book to the user's personal library, including the Firebase key.
            val libraryValues = ContentValues().apply {
                put(COLUMN_USER_ID_FK, userId)
                put(COLUMN_BOOK_ID_FK, bookId)
                put(COLUMN_STATUS, status)
                put(COLUMN_FIREBASE_KEY, firebaseKey) // Save the Firebase key for sync.
            }
            // Use CONFLICT_IGNORE to prevent crashing if the user already has the book.
            val result = db.insertWithOnConflict(USER_LIBRARY_TABLE_NAME, null, libraryValues, SQLiteDatabase.CONFLICT_IGNORE)

            db.setTransactionSuccessful() // Commit the transaction.
            return result != -1L
        } catch (e: Exception) {
            e.printStackTrace()
            return false
        } finally {
            db.endTransaction() // End the transaction (either commit or rollback).
            db.close() // Always close the database connection.
        }
    }

    /**
     * Searches for a book in the `books` table by its name and author.
     * @param db The readable database instance.
     * @param name The name of the book to find.
     * @param author The author of the book to find.
     * @return The ID of the book if found, otherwise -1.
     */
    private fun findBook(db: SQLiteDatabase, name: String, author: String): Long {
        var cursor: Cursor? = null
        try {
            cursor = db.query(
                BOOKS_TABLE_NAME,
                arrayOf(COLUMN_BOOK_ID),
                "$COLUMN_BOOK_NAME = ? AND $COLUMN_AUTHOR = ?",
                arrayOf(name, author),
                null, null, null
            )
            if (cursor.moveToFirst()) {
                return cursor.getLong(cursor.getColumnIndexOrThrow(COLUMN_BOOK_ID))
            }
        } finally {
            cursor?.close()
        }
        return -1L
    }

    /**
     * Retrieves all books belonging to a specific user.
     * It performs a JOIN between the `user_library` and `books` tables to gather all relevant data.
     * @param userId The ID of the user whose books are to be retrieved.
     * @return A list of `UserBook` objects, each representing a book in the user's library.
     */
    fun getBooksByUser(userId: Int): List<UserBook> {
        val bookList = mutableListOf<UserBook>()
        val db = this.readableDatabase
        // The JOIN query combines rows from both tables based on the book_id.
        val query = """
            SELECT
                lib.$COLUMN_LIBRARY_ID, lib.$COLUMN_USER_ID_FK, lib.$COLUMN_BOOK_ID_FK, lib.$COLUMN_STATUS, lib.$COLUMN_FIREBASE_KEY,
                b.$COLUMN_BOOK_NAME, b.$COLUMN_AUTHOR, b.$COLUMN_CATEGORY, b.$COLUMN_GENRE, b.$COLUMN_COVER_URI
            FROM
                $USER_LIBRARY_TABLE_NAME lib
            JOIN
                $BOOKS_TABLE_NAME b ON lib.$COLUMN_BOOK_ID_FK = b.$COLUMN_BOOK_ID
            WHERE
                lib.$COLUMN_USER_ID_FK = ?
        """.trimIndent()

        var cursor: Cursor? = null
        try {
            cursor = db.rawQuery(query, arrayOf(userId.toString()))
            if (cursor.moveToFirst()) {
                do {
                    // Safely get nullable values from the cursor.
                    val coverUriIndex = cursor.getColumnIndexOrThrow(COLUMN_COVER_URI)
                    val coverUri = if (cursor.isNull(coverUriIndex)) null else cursor.getString(coverUriIndex)

                    val statusIndex = cursor.getColumnIndexOrThrow(COLUMN_STATUS)
                    val status = if (cursor.isNull(statusIndex)) null else cursor.getString(statusIndex)
                    
                    val firebaseKeyIndex = cursor.getColumnIndexOrThrow(COLUMN_FIREBASE_KEY)
                    val firebaseKey = if (cursor.isNull(firebaseKeyIndex)) null else cursor.getString(firebaseKeyIndex)

                    // Create a UserBook object from the cursor row.
                    val book = UserBook(
                        id = cursor.getInt(cursor.getColumnIndexOrThrow(COLUMN_LIBRARY_ID)),
                        userId = cursor.getInt(cursor.getColumnIndexOrThrow(COLUMN_USER_ID_FK)),
                        bookId = cursor.getInt(cursor.getColumnIndexOrThrow(COLUMN_BOOK_ID_FK)),
                        status = status,
                        name = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_BOOK_NAME)),
                        author = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_AUTHOR)),
                        category = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_CATEGORY)),
                        genre = cursor.getString(cursor.getColumnIndexOrThrow(COLUMN_GENRE)),
                        coverUri = coverUri,
                        firebaseKey = firebaseKey // Retrieve the Firebase key
                    )
                    bookList.add(book)
                } while (cursor.moveToNext())
            }
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            cursor?.close()
            db.close()
        }
        return bookList
    }

    /**
     * Updates the reading status of a specific book in a user's library.
     * @param libraryId The unique ID of the entry in the `user_library` table.
     * @param status The new status to set (e.g., "Completed").
     * @return True if the update was successful, false otherwise.
     */
    fun updateBookStatus(libraryId: Int, status: String?): Boolean {
        val db = this.writableDatabase
        return try {
            val values = ContentValues().apply {
                if (status != null) {
                    put(COLUMN_STATUS, status)
                } else {
                    putNull(COLUMN_STATUS)
                }
            }
            val rows = db.update(
                USER_LIBRARY_TABLE_NAME,
                values,
                "$COLUMN_LIBRARY_ID = ?",
                arrayOf(libraryId.toString())
            )
            rows > 0 // The number of rows affected should be greater than 0 for a successful update.
        } catch (e: Exception) {
            e.printStackTrace()
            false
        } finally {
            db.close()
        }
    }

    /**
     * Updates the cover image URI for a book in the central `books` table.
     * @param bookId The ID of the book to update.
     * @param newCoverUri The new URI for the cover image.
     * @return True if the update was successful, false otherwise.
     */
    fun updateBookCover(bookId: Int, newCoverUri: String?): Boolean {
        val db = this.writableDatabase
        return try {
            val values = ContentValues().apply {
                put(COLUMN_COVER_URI, newCoverUri)
            }
            val rows = db.update(
                BOOKS_TABLE_NAME,
                values,
                "$COLUMN_BOOK_ID = ?",
                arrayOf(bookId.toString())
            )
            rows > 0
        } catch (e: Exception) {
            e.printStackTrace()
            false
        } finally {
            db.close()
        }
    }

    /**
     * Deletes a book from a user's library.
     * This only removes the entry from `user_library`, not from the central `books` table.
     * @param libraryId The ID of the `user_library` entry to delete.
     * @return True if the deletion was successful, false otherwise.
     */
    fun deleteBookFromLibrary(libraryId: Int): Boolean {
        val db = this.writableDatabase
        return try {
            val rows = db.delete(
                USER_LIBRARY_TABLE_NAME,
                "$COLUMN_LIBRARY_ID = ?",
                arrayOf(libraryId.toString())
            )
            rows > 0
        } catch (e: Exception) {
            e.printStackTrace()
            false
        } finally {
            db.close()
        }
    }
}
